name: Continuos Delivery

on:
  push:
    branches: [main]
    paths: ["**.nix"]

  pull_request:
    branches: [main]
    paths: ["**.nix"]

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake
        run: nix run nixpkgs#just upd

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
