name: Continuos Integration

on:
  push:
    branches: [main]
    paths: ["**.nix"]

  pull_request:
    branches: [main]
    paths: ["**.nix"]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v22
        with:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format code
        run: nix run nixpkgs#just fmt
